### PR TITLE
Miscellaneous things

### PR DESCRIPTION
**Pull request by Samisafool**
1. ~~Ported to PySimpleGUIQt~~ It doesn't work on Windows I'm coping
2. Change theme
2. Added dropdown menus
3. Allow double-click-execute on Linux (first line of python script)
4. Fix windows-specific bugs, someone please test!!!!!
5. Huge refactor, remove duplicated code, add variables, change ' to ", etc
6. General bugfixes (will crash less)

You need to install another package, check README.MD

### CODE REVIEW

**Comment by Samisafool** [comment]
Pls squash commits when merge ok thx

**Comment by ExoPlant** [comment]
Please supply a more informative title. I would say that you put what I think should be the title in the description

> I haven't tested this on windows 
This sort of thing should be in the description instead of the title

> Ported to pysimpleguiqt, added dropdown, fixed weird instance folder name bug
This describes what the PR does. Sort of thing that should be in the title

**Review by ExoPlant — CHANGES_REQUESTED** [review]
With the way git works, it won't commit a folder unless there's a file/folder in it. This is why I included a .instances file in the instances folder. By adding the `instances/*` line in the .gitignore file, you're stopping the instances folder from being pushed to the repo.

**Comment by Samisafool** [comment]
Done @ExoPlant

**Comment by Samisafool** [comment]
@ExoPlant Please go online on discord.

**Comment by Samisafool** [comment]
@ExoPlant

**Review by ExoPlant — APPROVED** [review]
Looks good, Windows still needs to be tested though

**Comment by Samisafool** [comment]
I have windows as a dual boot

**Comment by Samisafool** [comment]
On windows rn, brb gonna install python

**Comment by Samisafool** [comment]
pyside2 isnt on windows

**Comment by ExoPlant** [comment]
Okay, what do we do instead?

**Comment by ExoPlant** [comment]
Apparently pyside2 does work on windows

**Comment by Samisafool** [comment]
How and where

**Comment by ExoPlant** [comment]
I just read somewhere that it does

**Comment by ExoPlant** [comment]
Looks good now, except it never says to install PySimpleGUIQt and PySide2 if on linux

**Review by ExoPlant — CHANGES_REQUESTED** [review]
Please change the theme back to DarkGrey9 for now. I plan to implement a theme changer another time

**Comment by Samisafool** [comment]
I am done, please merge

**Review by ExoPlant — APPROVED** [review]
Thanks, will merge now

**Pull request merged**
