### PR TITLE
Refactor

### PR DESCRIPTION
**Pull request by Samisafool**
Add github actions

Update README.md

Update gitignore for PyCharm

\- Commit

Also rename python script, cleanup, deduplicate.

### CODE REVIEW

**Comment by Samisafool** [comment]
Don't merge yet, gonna add cxfreeze instead of pyinstaller

**Comment by ExoPlant** [comment]
Let me know when to

**Comment by Samisafool** [comment]
Yeah you can now

**Comment by Samisafool** [comment]
@ExoPlant

**Comment by ExoPlant** [comment]
I got my charger fixed btw

**Comment by Samisafool** [comment]
That's pog, can use discord?

**Comment by ExoPlant** [comment]
Yup

**Pull request merged**
