### PR TITLE
Idk

### LINKED ISSUE #14: Zip files should be added to .packwizignore
I'm making these for tracking bugs, don't worry about it exo

### LINKED ISSUE #15: Should have git integration
I'm making these for tracking bugs, don't worry about it exo

Adding .git to .packwizignore, initializing git repo, making automatic commits

### PR DESCRIPTION
**Pull request by Samisafool**
Fixes #14 
Fixes #15

### CODE REVIEW

**Comment by Samisafool** [comment]
Pls no merge yet

**Comment by Samisafool** [comment]
Ok merge now

**Comment by ExoPlant** [comment]
Looks good

**Comment by Samisafool** [comment]
Or does it??? (vsauce music)

**Pull request merged**
