### PR TITLE
Refactor

### PR DESCRIPTION
**Pull request by Samisafool**

### CODE REVIEW

**Comment by Samisafool** [comment]
Exo stop duping code AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA

**Comment by Samisafool** [comment]
Only Exporting to CF doesn't work, idk why

**Comment by ExoPlant** [comment]
Did you seriously rewrite my working window system?

**Comment by ExoPlant** [comment]
Note - I can't go on discord rn, so don't try continuing this there

**Comment by Samisafool** [comment]
Because it was jank.

**Comment by ExoPlant** [comment]
I guess I can get used to new system. The old system didn't break though. It worked fine

**Comment by ExoPlant** [comment]
I'll review it properly when I get home

**Comment by Samisafool** [comment]
It's not too different. Also I recommend reviewing it directly in my repo (https://github.com/Samisafool/packwiz-gui) instead of the PR. Much easier to look at.

**Pull request merged**
